# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b403faeefec25f4159a8f3143e8ad8975d4c4b864959ed366f6939c11117e300fb004389de74b568840db4df4097483573257f2607751c072ad4725cb8a65be

test:
  secret_key_base: b09c2682b85573aace4b5370f5f4f48a7b5f101f600e9987e0586f64d04cc13fb2aa29ddebf0f089749cd4a5e80d3fcaba1569d6c08d100325655aed80dfcf84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
